# This workflow will build a Go project after a new release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on: 
  workflow_dispatch:
  push:
    tags:
      - "releases/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Get
      run: go get -v ./...

    - name: Build
      run: |
        GOOS=windows GOARCH=amd64 go build -o main.exe ./...

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          main.exe
          LICENSE
